name: Respect CR Container APK

on:
  push:
    branches:
      - respect-nanohttpd

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          name: "Respect NanoHTTPD APK"
          tag_name: "respect-nanohttpd-apk-${{ github.run_number }}"
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
